# LDAP服务器配置
ldap:
  # 服务器连接信息
  server:
    url: 'ldap://ldap.forumsys.com:389'  # LDAP服务器地址
    use_ssl: false                 # 是否使用SSL
    timeout: 30                    # 连接超时时间（秒）

  # 认证信息
  auth:
    username: 'cn=read-only-admin,dc=example,dc=com'  # 管理员用户名
    password: 'password'            # 管理员密码
    authentication: 'SIMPLE'        # 认证方式：NTLM, SIMPLE, ANONYMOUS

  # 搜索配置
  search:
    base_dn: 'dc=example,dc=com'   # 基础DN
    default_filter: '(objectClass=person)' # 默认搜索过滤器
    attributes:                     # 需要返回的属性
      - cn
      - mail
      - department
      - title
      - telephoneNumber

  # 日志配置
  logging:
    level: 'INFO'                  # 日志级别：DEBUG, INFO, WARNING, ERROR
    format: '%(asctime)s - %(levelname)s - %(message)s'
    file: 'ldap.log'              # 日志文件路径 